config/routes.rb
Rails.application.routes.draw do
  mount ActiveAnalytics::Engine, at: "analytics"  # http://localhost:3000/analytics
  # Defines the root path route ("/")
  root "posts#index"
  get 'profiles/index'
  
  resources :likes, only: [:create, :destroy]
  resources :comments
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # devise_for :users
  resources :users, only:[:show]

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"

  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5, maximum: 100}
	validates :keywords, presence: true, length: { minimum: 5, maximum: 100}
	validates :description, presence: true, length: { minimum: 5, maximum: 500}

	has_many_attached :images
	belongs_to :user
	has_many :comments
	has_many :likes
	before_create :randomize_id
	

	def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000_000)
    end while User.where(id: self.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]
  include Pagy::Backend

  # GET /posts or /posts.json
  def index
    @posts = Post.order(:created_at => :asc)
    @pagy, @posts = pagy_countless(@posts, items: 1)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
  end

  def myposts
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, :user_id, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-10", style="margin: auto;">
  <h1>New post</h1>
  <%= form_with(model: post) do |form| %>
    <div>
    <% invalid = post.errors.include?(:title)%>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class:"form-control" %>
      <% if invalid %>
        <%= post.errors.full_messages_for(:title).join(" ,")%>
      <% end %>
    </div>
    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id%>
    </div>

    <div>
    <% invalid = post.errors.include?(:description)%>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description,class:"form-control" %>
      <% if invalid %>
        <%= post.errors.full_messages_for(:description).join(" ,")%>
      <% end %>
    </div>

    <div>
      <% invalid = post.errors.include?(:keywords)%>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords,class:"form-control" %>
      <% if invalid %>
        <%= post.errors.full_messages_for(:keywords).join(" ,")%>
      <% end %>
      <%= form.file_field :images, multiple:true %>
    </div>

    <div>
      <%= form.submit class:"btn btn-primary col-12 my-2" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <%= post.title %>
  </p>

  <p>
    <%= post.description %>
  </p>

  <p>
    <%= post.keywords %>
  </p>
  <p>
    <%= post.user.email %>
  </p>
  <p>
    <%#= link_to "", post, class: "post-link", style:"z-index:" %>
  </p>

  <% if user_signed_in? %>
    <% like = current_user.likes.find_by(post: post) %>
    <% if like.nil? %>
      <%= button_to "like", likes_path, params: { like: {post_id: post.id} }, method: :post %>
    <% else %>
      <%= button_to "Unlike", like_path(like), method: :delete %>
    <% end %>
  <% end %>
  <p><%= post.likes.count %> Likes </p>

  <% post.images.each do |image| %>
    <%= image_tag(image, style: "object-fit: contain; max-width: 50%; height: auto;") %>
  <% end %>
  <p>
  <%= post.title %>
  </p>
</div>
<p>
  <%= link_to post.user.email, post.user, style:"z-index:"%>
</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post")%>
<% if user_signed_in? %>
  <% current_user.follow_requests.each do |request| %>
    <%= request.followerable.email %> Wants to follow you 
    <%= button_to "Accept", accept_path(request.followerable) %>
    <%= button_to "Decline", decline_path(request.followerable) %>
  <% end %>
  Followers
  <% current_user.followers.each do |follower| %>
    <p> <b> <%= link_to follower.email, follower %> </b> </p>
  <% end %>
  Following
  <% current_user.following.each do |following| %>
    <p> <%= link_to following.email, following %> </p>
  <% end %>
<% end %>
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag :results, data: { turbo_action: 'advance' } do %>
  <div id="posts"></div>
  <%= turbo_frame_tag :pagination, loading: :lazy,
                      src: posts_path(format: :turbo_stream) %>
<% end %>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <% @posts.each do |post| %>
    <% if user_signed_in? %>
      <% if current_user.following?(post.user) %>
        <%= render post %>
      <% end %>
    <% end %>
  <% end %>
  <% if !user_signed_in? %>
    <% @posts.each do |post| %>
      <%= render post%>
    <% end %>
  <% end %>
<% end %><% if @pagy.next.present? %>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy,
                        src: posts_path(format: :turbo_stream, page: @pagy.next) %>
  <% end %>
<% end %>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
		<% if post.user.id == current_user.id %>
			<%= render post %>
		<% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <%= render "form", post: @post %>
</div>


<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= link_to "Back to posts", posts_path %>
<% if user_signed_in? %>
  <% if current_user.id == @post.user.id %>
    <div>
      <%= link_to "Edit this post", edit_post_path(@post) %>
      <%= link_to "Back to posts", posts_path %>
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>
  <% end %>
<% end %>

<%= render 'comments/form', comment: @comment %>

<%= @post.comments.each do |comment| %>
  <%= comment.text %>
  <br>
<% end %>

app/views/posts/users.html.erb
<div id="posts" class="text-center">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>